### ISSUE TITLE
See null result for query on Windows

### ISSUE THREAD

**Issue by IlyaBoyur** [AlexCovizzi/vscode-sqlite#132]
Hi Alex.
I searched thrrough closed issues and I did not find my case so I post my problem here. 
Instead of query output I see always null.
What I do:
1) install extention
2) open simple sql file with this text:  SELECT * FROM posts_post ORDER BY id;
3)  call Sqlite: Run Query, select my db.sqlite3 file 
This is output for developer console on  Sqlite: Run Query:
```
[Extension Host][20:45:03][vscode-sqlite][DEBUG] Statements:
[{"sql":"SELECT * \nFROM posts_post\nORDER BY id;","position":{"start":[0,0],"end":[2,11]},"type":"SELECT"}]
[Extension Host] rejected promise not handled within 1 second
 ERR this.panel.webview.asWebviewUri is not a function: TypeError: this.panel.webview.asWebviewUri is not a function
	at l.show (C:\Users\iboju\.vscode\extensions\alexcvzz.vscode-sqlite-0.9.0\dist\extension.js:1:41619)
	at l.display (C:\Users\iboju\.vscode\extensions\alexcvzz.vscode-sqlite-0.9.0\dist\extension.js:1:38940)
	at _ (C:\Users\iboju\.vscode\extensions\alexcvzz.vscode-sqlite-0.9.0\dist\extension.js:1:18633)
	at x (C:\Users\iboju\.vscode\extensions\alexcvzz.vscode-sqlite-0.9.0\dist\extension.js:1:17884)
	at module.exports.C.then.e (C:\Users\iboju\.vscode\extensions\alexcvzz.vscode-sqlite-0.9.0\dist\extension.js:1:17925)
```

**Comment by AlexCovizzi** [comment]
Hi @IlyaBoyur, what version of VSCode are you using?

**Comment by IlyaBoyur** [comment]
I have just updated to the latest version and issued has been resolved, everything works fine for now))
That shall be placed in stupidest issues column)) Iliterally wasted few days trying to figure out the problem)
Version now:
Version: 1.50.0 (system setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362
